### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by erichVK5** [AiTechEye/was#1]
Would it be possible to have some installation instructions provided.

I would like to use this in a computing lab to teach coding to primary school students on linux desktops.

Regards,

Erich

**Comment by erichVK5** [comment]
OK, installation is sorted, via the online search dialogue within minetest. Some sort of instruction for installing into ~/./minetest would still be useful.

Next problem, you describe "Check out the GUI for instructions". I can't see where in the minetest interface or implements dialogue the WAS capability can be launched.

Any chance of some guidance either text based or screenshots on how to launch WAS from the GUI? 

Cheers,

Erich.

**Comment by AiTechEye** [comment]
there is a run button in right top, and it seems like it just shows some green text when you pressing an option in the list.
WAS do not  need any other mods to work, but it works with the other mods, eg send signals by mesecon & digilines wires

you can see more info at the [readme](https://github.com/AiTechEye/was/blob/master/README.md)

by the way, dont base too much on it, cuz it has its own speical language that reminds of lua, the whole idea of the mod was to try to make my own kind of language for fun, which was hard to do.
i do not remmeber how well the mod works, so its just to try it out.
but yeah, it can be a base to start learning code, the language is just simple.
